### ISSUE TITLE
memory error in running solution 5 (no issues with previous sols)

### ISSUE THREAD

**Issue by yipcma** [minerva-ml/open-solution-data-science-bowl-2018#70]
```
    for batch_id, data in enumerate(batch_gen):
  File "/home/andrew/anaconda3/envs/neptune/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 417, in __iter__
    return DataLoaderIter(self)
  File "/home/andrew/anaconda3/envs/neptune/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 234, in __init__
    w.start()
  File "/home/andrew/anaconda3/envs/neptune/lib/python3.5/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/home/andrew/anaconda3/envs/neptune/lib/python3.5/multiprocessing/context.py", line 212, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/home/andrew/anaconda3/envs/neptune/lib/python3.5/multiprocessing/context.py", line 274, in _Popen
    return Popen(process_obj)
  File "/home/andrew/anaconda3/envs/neptune/lib/python3.5/multiprocessing/popen_spawn_posix.py", line 33, in __init__
    super().__init__(process_obj)
  File "/home/andrew/anaconda3/envs/neptune/lib/python3.5/multiprocessing/popen_fork.py", line 20, in __init__
    self._launch(process_obj)
  File "/home/andrew/anaconda3/envs/neptune/lib/python3.5/multiprocessing/popen_spawn_posix.py", line 48, in _launch
    reduction.dump(process_obj, fp)
  File "/home/andrew/anaconda3/envs/neptune/lib/python3.5/multiprocessing/reduction.py", line 59, in dump
    ForkingPickler(file, protocol).dump(obj)
MemoryError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/andrew/anaconda3/envs/neptune/lib/python3.5/site-packages/deepsense/neptune/job_wrapper.py", line 111, in <module>
    execute()
  File "/home/andrew/anaconda3/envs/neptune/lib/python3.5/site-packages/deepsense/neptune/job_wrapper.py", line 107, in execute
    raise ExperimentExecutionException("Exception during experiment execution", ex)
deepsense.neptune.exceptions.ExperimentExecutionException: ('Exception during experiment execution', MemoryError())
Calculated experiment snapshot size: 0 Bytes
Process exited with return code 1.
```

**Comment by kamil-kaczmarek** [comment]
Hey @yipcma 

This is known issue and I'm working on it. I will get back to you with solution.
