### ISSUE TITLE
predict/evaluate is not working

### ISSUE THREAD

**Issue by 7rick03ligh7** [minerva-ml/open-solution-data-science-bowl-2018#71]
python main.py -- predict_pipeline --pipeline_name unet_multitask

neptune: Executing in Offline Mode.
neptune: Executing in Offline Mode.
neptune: Executing in Offline Mode.
2018-04-07 08-49-46 steps >>> step reader_inference adapting inputs
2018-04-07 08-49-46 steps >>> step reader_inference loading transformer...
2018-04-07 08-49-46 steps >>> step reader_inference transforming...
100%|██████████████████████████████████████████| 65/65 [00:00<00:00, 131.16it/s]
2018-04-07 08-49-47 steps >>> step reader_inference caching outputs...
2018-04-07 08-49-47 steps >>> step loader adapting inputs
2018-04-07 08-49-47 steps >>> step loader loading transformer...
2018-04-07 08-49-47 steps >>> step loader transforming...
2018-04-07 08-49-47 steps >>> step loader caching outputs...
2018-04-07 08-49-47 steps >>> step unet_multitask unpacking inputs
2018-04-07 08-49-47 steps >>> step unet_multitask fitting and transforming...
2018-04-07 08-49-47 steps >>> initializing model weights...
2018-04-07 08-49-50 steps >>> starting training...
2018-04-07 08-49-50 steps >>> initial lr: 0.0001
2018-04-07 08-49-50 steps >>> epoch 0 ...
Traceback (most recent call last):
  File "main.py", line 181, in <module>
    action()
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "main.py", line 125, in predict_pipeline
    _predict_pipeline(pipeline_name)
  File "main.py", line 141, in _predict_pipeline
    output = pipeline.transform(data)
  File "/content/open-solution-data-science-bowl-2018/steps/base.py", line 141, in transform
    step_inputs[input_step.name] = input_step.fit_transform(data)
  File "/content/open-solution-data-science-bowl-2018/steps/base.py", line 92, in fit_transform
    step_inputs[input_step.name] = input_step.fit_transform(data)
  File "/content/open-solution-data-science-bowl-2018/steps/base.py", line 92, in fit_transform
    step_inputs[input_step.name] = input_step.fit_transform(data)
  File "/content/open-solution-data-science-bowl-2018/steps/base.py", line 98, in fit_transform
    step_output_data = self._cached_fit_transform(step_inputs)
  File "/content/open-solution-data-science-bowl-2018/steps/base.py", line 109, in _cached_fit_transform
    step_output_data = self.transformer.fit_transform(**step_inputs)
  File "/content/open-solution-data-science-bowl-2018/steps/base.py", line 241, in fit_transform
    self.fit(*args, **kwargs)
  File "/content/open-solution-data-science-bowl-2018/steps/pytorch/models.py", line 63, in fit
    metrics = self._fit_loop(data)
  File "/content/open-solution-data-science-bowl-2018/steps/pytorch/models.py", line 89, in _fit_loop
    outputs_batch = self.model(X)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/content/open-solution-data-science-bowl-2018/steps/pytorch/architectures/unet.py", line 188, in forward
    x = self.input_block(x)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/container.py", line 67, in forward
    input = module(input)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/conv.py", line 282, in forward
    self.padding, self.dilation, self.groups)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py", line 85, in conv2d
    raise ValueError("Expected 4D tensor as input, got {}D tensor instead.".format(input.dim()))
**ValueError: Expected 4D tensor as input, got 3D tensor instead.**
Sentry is attempting to send 1 pending error messages
Waiting up to 10 seconds
Press Ctrl-C to quit

**Comment by hongta** [comment]
using master branch, same issue here

**Comment by dongdonghy** [comment]
I also met this error too, is there any solution here? @hongta @DiggiDon.

**Comment by DiggiDon** [comment]
I hope the contributors will help us)

**Comment by kamil-kaczmarek** [comment]
hi @DiggiDon @hongta @dongdonghy 
I am looking at this now -> will get back to you soon.

**Comment by kamil-kaczmarek** [comment]
hey @DiggiDon, what is your batch size?

**Comment by DiggiDon** [comment]
@kamil-kaczmarek  All configurations is default as in repository
